"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {agentEvidenceSourceLabel,evidenceSourceLabel,questionIntentLabel,scoreLabel} from "@/lib/format";
import {applicationDraftQuestions,getAgentAnalysisFixture,getApplicationDraftFixture,getSemanticMatchFixture,hasAiInsightDemo} from "@/lib/fixtures/ai-insight";
import type {AiInsightDemoJob} from "@/lib/fixtures/ai-insight";
import type {QuestionDraftResult} from "@/lib/types";
import styles from "../../App.module.css";
import local from "./page.module.css";
import MatchPanel from "./MatchPanel";
const DEMO_TOOLTIP="데모 환경에서는 저장된 예시 분석 결과를 보여줍니다";
const EvidenceTags=({values,agent=false}:{values:string[];agent?:boolean})=><div className={local.tags}>{values.map(value=><span key={value}>{agent?agentEvidenceSourceLabel[value as keyof typeof agentEvidenceSourceLabel]:evidenceSourceLabel[value as keyof typeof evidenceSourceLabel]}</span>)}</div>;
const DemoNotice=({demoJob}:{demoJob:AiInsightDemoJob})=> <p className={local.demoNotice}>이 공고에는 준비된 데모 분석이 없습니다. 데모 분석은 <Link href={`/jobs/${demoJob.id}`}>{demoJob.title}</Link>에서 확인할 수 있습니다.</p>;
function Stage({title,description,children,demo=true}:{title:string;description:string;children:React.ReactNode;demo?:boolean}){return <li><div className={local.stageHeading}><div><h3>{title}</h3><p>{description}</p></div><span title={demo?DEMO_TOOLTIP:undefined}>{demo?"데모 분석":"실시간 계산"}</span></div>{children}</li>}
function Toggle({open,setOpen}:{open:boolean;setOpen:(value:boolean)=>void}){return <button className={`${styles.button} ${styles.buttonSecondary}`} type="button" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?"결과 닫기":"결과 보기"}</button>}
function SemanticResult(){const result=getSemanticMatchFixture();const groups=[{label:"경험",items:result.experienceMatches},{label:"자격",items:result.certificationMatches},{label:"학력",items:result.educationMatches},{label:"수상",items:result.awardMatches}];return <div className={local.resultBlock}><div className={local.scoreRow}><span>의미 기반 연관도</span><strong>{scoreLabel(result.semanticScore)}/1.0</strong></div><p className={local.caveat}>공고와 경험 사이의 의미적 연결을 정리한 참고 지표입니다.</p>{groups.map(({label,items})=><section key={label} className={local.resultSection}><h4>{label}</h4>{items.map(item=><article key={`${item.type}-${item.id}`} className={local.evidenceCard}><div><strong>{item.title}</strong><span className={styles.mono}>연관도 {scoreLabel(item.score)}</span></div><p>{item.reason}</p><EvidenceTags values={item.evidence}/></article>)}</section>)}<section className={local.resultSection}><h4>추가 확인 사항</h4><ul>{result.gaps.map(gap=><li key={gap}>{gap}</li>)}</ul></section></div>}
function AgentResult(){const result=getAgentAnalysisFixture();const groups=[{label:"자격",items:result.recommendedCertifications},{label:"학력",items:result.recommendedEducations},{label:"수상",items:result.recommendedAwards}];return <div className={local.resultBlock}><h4>{result.positioningHeadline}</h4><p>{result.roleSummary}</p><p>{result.positioningSummary}</p><section className={local.resultSection}><h4>핵심 메시지</h4><p>{result.primaryMessage}</p><ul>{result.secondaryMessages.map(message=><li key={message}>{message}</li>)}</ul></section><section className={local.resultSection}><h4>추천 경험</h4>{result.recommendedExperiences.map(item=><article key={item.id} className={local.evidenceCard}><div><strong>{item.priority}. {item.title}</strong><span className={styles.mono}>연관도 {scoreLabel(item.semanticMatchScore)}</span></div><p>{item.reason}</p><ul>{item.emphasisPoints.map(point=><li key={point}>{point}</li>)}</ul><EvidenceTags values={item.evidence} agent/></article>)}</section>{groups.map(({label,items})=><section key={label} className={local.resultSection}><h4>추천 {label}</h4>{items.map(item=><article key={item.id} className={local.evidenceCard}><div><strong>{item.title}</strong><span className={styles.mono}>연관도 {scoreLabel(item.semanticMatchScore)}</span></div><p>{item.reason}</p><EvidenceTags values={item.evidence} agent/></article>)}</section>)}<div className={local.twoColumns}><section><h4>주의할 표현</h4><ul>{result.avoidOrBeCareful.map(item=><li key={item}>{item}</li>)}</ul></section><section><h4>보완할 점</h4><ul>{result.gaps.map(item=><li key={item}>{item}</li>)}</ul></section></div></div>}
function DraftCard({result}:{result:QuestionDraftResult}){const [copied,setCopied]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);const copy=async()=>{await navigator.clipboard.writeText(result.draft);setCopied(true);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setCopied(false),2000)};return <article className={local.draftCard}><div className={local.draftHeading}><div><span className={local.intent}>{questionIntentLabel[result.primaryIntent]}{result.secondaryIntents.length>0&&` · ${result.secondaryIntents.map(value=>questionIntentLabel[value]).join(" · ")}`}</span><h4>{applicationDraftQuestions[result.questionId]}</h4></div><span className={`${styles.mono} ${result.limitExceeded?local.warning:""}`}>{result.characterCount}{result.maxLength!==null?` / ${result.maxLength}`:""}자</span></div>{result.missingCompanyContext&&<p className={local.caveat}>공고에 회사 소개 정보가 없어 이 부분은 일반적인 문장으로 채웠습니다.</p>}<h5>구성</h5><ol>{result.outline.map(item=><li key={item}>{item}</li>)}</ol><div className={local.draftBody}>{result.draft}</div><button className={`${styles.button} ${styles.buttonSecondary}`} type="button" onClick={copy}>{copied?"복사됨":"복사"}</button></article>}
function ApplicationResult(){const result=getApplicationDraftFixture();return <div className={local.resultBlock}><h4>전체 전략</h4><p>{result.overallStrategy.primaryPositioning}</p>{result.overallStrategy.warnings.map(warning=><p key={warning} className={local.caveat}>{warning}</p>)}<div className={local.distribution}><strong>경험 배치</strong>{result.overallStrategy.experienceDistribution.map(item=><div key={item.experienceId}><span>{item.title}</span><span>{item.usedInQuestionIds.join(", ")}</span></div>)}</div>{result.questions.map(question=><DraftCard key={question.questionId} result={question}/>)}</div>}
export default function AiInsightWorkflow({jobId,demoJob}:{jobId:string;demoJob:AiInsightDemoJob}){const demo=hasAiInsightDemo(jobId);const [semanticOpen,setSemanticOpen]=useState(false);const [agentOpen,setAgentOpen]=useState(false);const [draftOpen,setDraftOpen]=useState(false);return <section className={local.insights}><h2>AI 인사이트</h2><p>공고와 내 경험의 연결점을 단계별로 확인합니다.</p><ol className={`${styles.timeline} ${local.insightTimeline}`}><Stage title="기본 적합도" description="PKB와 공고 카테고리의 근거 기반 연결을 현재 데이터로 계산합니다." demo={false}><MatchPanel jobId={jobId}/></Stage><Stage title="AI 심층 분석" description="문자열 비교에서 놓칠 수 있는 경험의 의미적 연결을 정리합니다.">{demo?<><Toggle open={semanticOpen} setOpen={setSemanticOpen}/>{semanticOpen&&<SemanticResult/>}</>:<DemoNotice demoJob={demoJob}/>}</Stage><Stage title="지원 전략 분석" description="강조할 경험과 정직하게 밝혀야 할 한계를 함께 정리합니다.">{demo?<><Toggle open={agentOpen} setOpen={setAgentOpen}/>{agentOpen&&<AgentResult/>}</>:<DemoNotice demoJob={demoJob}/>}</Stage><Stage title="자기소개서 초안" description="저장된 근거를 서로 다른 문항 의도에 맞춰 구성한 예시입니다.">{demo?<><Toggle open={draftOpen} setOpen={setDraftOpen}/>{draftOpen&&<ApplicationResult/>}</>:<DemoNotice demoJob={demoJob}/>}</Stage></ol></section>}
