import {awards,certifications,educations,experiences} from "@/lib/fixtures/data";
import type {Award,Certification,Education,Experience,ExperienceDetail,Page} from "@/lib/types";
import {apiBaseUrl,deleteRequest,fixturePage,getJson,patchJson,postJson,queryString} from "./client";
export async function getExperiences(q:{type?:string;keyword?:string;page?:number;size?:number}={}):Promise<Page<Experience>>{if(apiBaseUrl)return getJson(`/api/career/experiences?${queryString(q)}`);const list=experiences.filter(e=>(!q.type||e.type===q.type)&&(!q.keyword||`${e.title} ${e.summary}`.includes(q.keyword)));return fixturePage(list,q.page??0,q.size??20)}
export async function getExperience(id:string):Promise<ExperienceDetail>{if(apiBaseUrl)return getJson(`/api/career/experiences/${encodeURIComponent(id)}`);const item=experiences.find(e=>e.id===id);if(!item)throw new Error("경험을 찾을 수 없습니다.");return item}
export async function getCertifications(page=0,size=20):Promise<Page<Certification>>{return apiBaseUrl?getJson(`/api/career/certifications?${queryString({page,size})}`):fixturePage(certifications,page,size)}
export async function getEducations(page=0,size=20):Promise<Page<Education>>{return apiBaseUrl?getJson(`/api/career/educations?${queryString({page,size})}`):fixturePage(educations,page,size)}
export async function getAwards(page=0,size=20):Promise<Page<Award>>{return apiBaseUrl?getJson(`/api/career/awards?${queryString({page,size})}`):fixturePage(awards,page,size)}
export type ExperienceInput={type:Experience["type"];title:string;organization?:string;role?:string;startDate?:string;endDate?:string;summary?:string;detail?:string;bullets:{bulletType:ExperienceDetail["bullets"][number]["bulletType"];content:string}[];tags:string[]};
export type CertificationInput={name:string;issuer?:string;acquiredDate?:string;expirationDate?:string;credentialId?:string;description?:string};
export type EducationInput={institution:string;major?:string;degree?:Education["degree"];status?:Education["status"];startDate?:string;endDate?:string;gpa?:number;gpaScale?:number;description?:string};
export type AwardInput={title:string;issuer?:string;awardedDate?:string;description?:string};
const path=(resource:string,id?:string)=>`/api/career/${resource}${id?`/${encodeURIComponent(id)}`:""}`;
export const createExperienceRequest=(input:ExperienceInput)=>postJson<ExperienceDetail>(path("experiences"),input);export const updateExperienceRequest=(id:string,input:ExperienceInput)=>patchJson<ExperienceDetail>(path("experiences",id),input);export const deleteExperienceRequest=(id:string)=>deleteRequest(path("experiences",id));
export const createCertificationRequest=(input:CertificationInput)=>postJson<Certification>(path("certifications"),input);export const updateCertificationRequest=(id:string,input:CertificationInput)=>patchJson<Certification>(path("certifications",id),input);export const deleteCertificationRequest=(id:string)=>deleteRequest(path("certifications",id));
export const createEducationRequest=(input:EducationInput)=>postJson<Education>(path("educations"),input);export const updateEducationRequest=(id:string,input:EducationInput)=>patchJson<Education>(path("educations",id),input);export const deleteEducationRequest=(id:string)=>deleteRequest(path("educations",id));
export const createAwardRequest=(input:AwardInput)=>postJson<Award>(path("awards"),input);export const updateAwardRequest=(id:string,input:AwardInput)=>patchJson<Award>(path("awards",id),input);export const deleteAwardRequest=(id:string)=>deleteRequest(path("awards",id));
