CREATE TABLE source_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255),
    document_type VARCHAR(50) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    raw_text VARCHAR(50000) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
