CREATE TABLE import_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_batch_id BIGINT NOT NULL REFERENCES import_batches(id),
    target_type VARCHAR(30) NOT NULL,
    payload VARCHAR(10000) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_entity_id BIGINT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    reviewed_at TIMESTAMP(6) WITH TIME ZONE
);
