ALTER TABLE job_recommendation_notifications
    ADD COLUMN sent_at TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN last_attempt_at TIMESTAMP(6) WITH TIME ZONE,
    ADD COLUMN failure_code VARCHAR(40);

CREATE TABLE kakao_oauth_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refresh_token VARCHAR(500) NOT NULL,
    refresh_token_expires_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
