CREATE TABLE job_postings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    employment_type VARCHAR(255),
    job_category VARCHAR(255),
    location VARCHAR(255),
    application_start_at DATE,
    application_end_at DATE,
    source VARCHAR(255) NOT NULL,
    source_url VARCHAR(2048),
    external_id VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
