ALTER TABLE job_postings ADD COLUMN detail_fetched_at TIMESTAMP(6) WITH TIME ZONE;

CREATE TABLE recruitment_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id BIGINT NOT NULL REFERENCES job_postings(id),
    recrut_step_sn BIGINT NOT NULL,
    sort_no INTEGER,
    min_step_sn BIGINT,
    max_step_sn BIGINT,
    step_group_name VARCHAR(255),
    competition_rate DOUBLE PRECISION,
    applicant_count INTEGER,
    recruit_count INTEGER,
    occurred_at_raw VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_recruitment_steps_recrut_step_sn UNIQUE (recrut_step_sn)
);
CREATE INDEX idx_recruitment_steps_job_posting_id ON recruitment_steps(job_posting_id);

CREATE TABLE attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id BIGINT NOT NULL REFERENCES job_postings(id),
    recrut_atch_file_no BIGINT NOT NULL,
    sort_no INTEGER,
    file_name VARCHAR(255),
    file_type VARCHAR(255),
    url VARCHAR(2048),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_attachments_recrut_atch_file_no UNIQUE (recrut_atch_file_no)
);
CREATE INDEX idx_attachments_job_posting_id ON attachments(job_posting_id);
