CREATE TABLE job_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id BIGINT NOT NULL REFERENCES job_postings(id),
    status VARCHAR(50) NOT NULL,
    memo VARCHAR(2000),
    applied_at DATE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_job_applications_job_posting_id UNIQUE (job_posting_id)
);
