CREATE TABLE application_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_application_id BIGINT NOT NULL REFERENCES job_applications(id) ON DELETE CASCADE,
    stage_type VARCHAR(50) NOT NULL,
    label VARCHAR(100),
    sort_order INTEGER NOT NULL,
    scheduled_at TIMESTAMP(6),
    result VARCHAR(50) NOT NULL,
    memo VARCHAR(1000),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_application_stages_application_sort_order UNIQUE (job_application_id, sort_order)
);
