CREATE TABLE career_experiences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(200) NOT NULL,
    organization VARCHAR(200),
    role VARCHAR(200),
    start_date DATE,
    end_date DATE,
    summary VARCHAR(500),
    detail VARCHAR(4000),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE experience_bullets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    career_experience_id BIGINT NOT NULL REFERENCES career_experiences(id) ON DELETE CASCADE,
    bullet_type VARCHAR(50),
    content VARCHAR(1000) NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_experience_bullets_experience_sort_order UNIQUE (career_experience_id, sort_order)
);

CREATE TABLE experience_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    career_experience_id BIGINT NOT NULL REFERENCES career_experiences(id) ON DELETE CASCADE,
    keyword VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uk_experience_tags_experience_keyword
    ON experience_tags (career_experience_id, LOWER(keyword));
