CREATE TABLE career_certifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    issuer VARCHAR(200),
    acquired_date DATE,
    expiration_date DATE,
    credential_id VARCHAR(100),
    description VARCHAR(2000),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
