CREATE TABLE career_educations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution VARCHAR(200) NOT NULL,
    major VARCHAR(200),
    degree VARCHAR(50),
    status VARCHAR(50),
    start_date DATE,
    end_date DATE,
    gpa NUMERIC(5,2),
    gpa_scale NUMERIC(5,2),
    description VARCHAR(2000),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
