package com.careerops.backend.applicationdraft;

import com.careerops.backend.agent.AgentAnalysisService;
import com.careerops.backend.agent.dto.AgentAnalysisResponse;
import com.careerops.backend.agent.dto.ExperienceRecommendation;
import com.careerops.backend.agent.llm.AgentAnalysisException;
import com.careerops.backend.applicationdraft.dto.*;
import com.careerops.backend.applicationdraft.llm.*;
import com.careerops.backend.applicationdraft.llm.dto.*;
import com.careerops.backend.applicationdraft.llm.dto.RawApplicationDraftRepairResult.RawQuestionRepair;
import com.careerops.backend.career.*;
import com.careerops.backend.job.*;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.junit.jupiter.api.*;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;
import java.time.Instant;
import java.util.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

class ApplicationDraftServiceTest {
    JobPostingRepository jobs;AgentAnalysisService analysis;CareerExperienceRepository experiences;ExperienceTagRepository tags;ExperienceBulletRepository bullets;CertificationRepository certifications;EducationRepository educations;AwardRepository awards;ApplicationDraftClient client;ApplicationDraftService service;CareerExperience exp;
    @BeforeEach void setUp(){jobs=mock(JobPostingRepository.class);analysis=mock(AgentAnalysisService.class);experiences=mock(CareerExperienceRepository.class);tags=mock(ExperienceTagRepository.class);bullets=mock(ExperienceBulletRepository.class);certifications=mock(CertificationRepository.class);educations=mock(EducationRepository.class);awards=mock(AwardRepository.class);client=mock(ApplicationDraftClient.class);
        var job=new JobPosting("c","j","regular","new","degree","OPEN","i","IT","s",null,null,"MANUAL","url","id");ReflectionTestUtils.setField(job,"id",1L);when(jobs.findById(1L)).thenReturn(Optional.of(job));when(analysis.analyze(1L)).thenReturn(strategy());
        exp=new CareerExperience(ExperienceType.PROJECT,"추천 밖 협업 경험",null,null,null,null,"summary","detail");ReflectionTestUtils.setField(exp,"id",9L);when(experiences.findAll()).thenReturn(List.of(exp));when(tags.findByCareerExperienceIdIn(anyList())).thenReturn(List.of());when(bullets.findByCareerExperienceIdIn(anyList())).thenReturn(List.of());when(certifications.findAll()).thenReturn(List.of());when(educations.findAll()).thenReturn(List.of());when(awards.findAll()).thenReturn(List.of());
        service=new ApplicationDraftService(jobs,analysis,experiences,tags,bullets,certifications,educations,awards,client,new SimpleMeterRegistry());}
    @Test void missingJobStopsBothCalls(){assertThatThrownBy(()->service.draft(2L,request("q",null))).isInstanceOf(ResponseStatusException.class);verifyNoInteractions(analysis,client);}
    @Test void duplicateRequestIdIsBadRequestBeforeCalls(){var req=new ApplicationDraftRequest(List.of(new QuestionRequest("q","a",null),new QuestionRequest("q","b",null)));assertThatThrownBy(()->service.draft(1L,req)).isInstanceOf(ResponseStatusException.class);verifyNoInteractions(analysis,client);}
    @Test void outsideAgentRecommendationsButApprovedFullPkbIsAcceptedAndIdsAreDeduplicated(){when(analysis.analyze(1L)).thenReturn(strategyWithDifferentRecommendation());when(client.plan(any(),any(),anyList(),anyMap(),anyMap(),anyList(),anyList(),anyList(),anyList())).thenReturn(raw(draft("q",9L,List.of(9L,9L),"초안")));var out=service.draft(1L,request("q",null));assertThat(out.questions()).hasSize(1);assertThat(out.questions().getFirst().primaryExperienceId()).isEqualTo(9L);assertThat(out.questions().getFirst().supportingExperienceIds()).containsExactly(9L);assertThat(out.overallStrategy().experienceDistribution().getFirst().title()).isEqualTo("추천 밖 협업 경험");verify(client,never()).repair(anyList(),anyList());}
    @Test void unknownAndDuplicateQuestionResultsFailAllOrNothing(){when(client.plan(any(),any(),anyList(),anyMap(),anyMap(),anyList(),anyList(),anyList(),anyList())).thenReturn(raw(draft("other",9L,List.of(),"x")));assertThatThrownBy(()->service.draft(1L,request("q",null))).isInstanceOf(ApplicationDraftException.class).extracting("reason").isEqualTo(ApplicationDraftException.Reason.UNKNOWN_QUESTION_ID);}
    @Test void duplicateQuestionResultIsNotDeduplicated(){var d=draft("q",9L,List.of(),"x");when(client.plan(any(),any(),anyList(),anyMap(),anyMap(),anyList(),anyList(),anyList(),anyList())).thenReturn(new RawApplicationDraftResult(new RawOverallStrategy("p",List.of()),List.of(d,d)));assertThatThrownBy(()->service.draft(1L,request("q",null))).isInstanceOf(ApplicationDraftException.class).extracting("reason").isEqualTo(ApplicationDraftException.Reason.DUPLICATE_QUESTION_RESULT);}
    @Test void unknownApprovedPkbIdFails(){when(client.plan(any(),any(),anyList(),anyMap(),anyMap(),anyList(),anyList(),anyList(),anyList())).thenReturn(raw(draft("q",99L,List.of(),"x")));assertThatThrownBy(()->service.draft(1L,request("q",null))).isInstanceOf(ApplicationDraftException.class).extracting("reason").isEqualTo(ApplicationDraftException.Reason.UNKNOWN_CANDIDATE_ID);}
    @Test void repairSuccessUpdatesOnlyDraftAndLength(){when(client.plan(any(),any(),anyList(),anyMap(),anyMap(),anyList(),anyList(),anyList(),anyList())).thenReturn(raw(draft("q",9L,List.of(),"123456")));when(client.repair(anyList(),anyList())).thenReturn(new RawApplicationDraftRepairResult(List.of(new RawQuestionRepair("q","123"))));var q=service.draft(1L,request("q",3)).questions().getFirst();assertThat(q.draft()).isEqualTo("123");assertThat(q.characterCount()).isEqualTo(3);assertThat(q.limitExceeded()).isFalse();verify(client,times(1)).repair(anyList(),anyList());}
    @Test void repairProviderFailureFallsBackWithLimitExceeded(){when(client.plan(any(),any(),anyList(),anyMap(),anyMap(),anyList(),anyList(),anyList(),anyList())).thenReturn(raw(draft("q",9L,List.of(),"123456")));when(client.repair(anyList(),anyList())).thenThrow(new ApplicationDraftException(ApplicationDraftException.Reason.NETWORK_TIMEOUT));var q=service.draft(1L,request("q",3)).questions().getFirst();assertThat(q.draft()).isEqualTo("123456");assertThat(q.limitExceeded()).isTrue();}
    @Test void pkbEmptyConflictIsPropagatedAndPlanIsNotCalled(){when(analysis.analyze(1L)).thenThrow(new ResponseStatusException(HttpStatus.CONFLICT,"empty"));assertThatThrownBy(()->service.draft(1L,request("q",null))).isInstanceOfSatisfying(ResponseStatusException.class,e->assertThat(e.getStatusCode()).isEqualTo(HttpStatus.CONFLICT));verify(client,never()).plan(any(),any(),anyList(),anyMap(),anyMap(),anyList(),anyList(),anyList(),anyList());}
    @Test void agentAnalysisFailureStopsBeforePlan(){when(analysis.analyze(1L)).thenThrow(new AgentAnalysisException(AgentAnalysisException.Reason.NETWORK_TIMEOUT));assertThatThrownBy(()->service.draft(1L,request("q",null))).isInstanceOfSatisfying(ApplicationDraftException.class,e->assertThat(e.reason()).isEqualTo(ApplicationDraftException.Reason.AGENT_ANALYSIS_FAILED));verify(client,never()).plan(any(),any(),anyList(),anyMap(),anyMap(),anyList(),anyList(),anyList(),anyList());}
    @Test void fourQuestionsAreMatchedByIdDespiteDifferentProviderOrder(){var request=new ApplicationDraftRequest(List.of(new QuestionRequest("support","지원동기",null),new QuestionRequest("job","직무역량",null),new QuestionRequest("problem","문제해결",null),new QuestionRequest("team","협업",null)));when(client.plan(any(),any(),anyList(),anyMap(),anyMap(),anyList(),anyList(),anyList(),anyList())).thenReturn(raw(draft("team",9L,List.of(),"d4"),draft("problem",9L,List.of(),"d3"),draft("support",9L,List.of(),"d1"),draft("job",9L,List.of(),"d2")));var out=service.draft(1L,request);assertThat(out.questions()).hasSize(4);assertThat(out.questions()).extracting(QuestionDraftResult::questionId).containsExactly("support","job","problem","team");assertThat(out.questions()).extracting(QuestionDraftResult::draft).containsExactly("d1","d2","d3","d4");verify(client,times(1)).plan(any(),any(),anyList(),anyMap(),anyMap(),anyList(),anyList(),anyList(),anyList());}
    @Test void missingQuestionResultFails(){var request=new ApplicationDraftRequest(List.of(new QuestionRequest("q1","a",null),new QuestionRequest("q2","b",null)));when(client.plan(any(),any(),anyList(),anyMap(),anyMap(),anyList(),anyList(),anyList(),anyList())).thenReturn(raw(draft("q1",9L,List.of(),"x")));assertThatThrownBy(()->service.draft(1L,request)).isInstanceOfSatisfying(ApplicationDraftException.class,e->assertThat(e.reason()).isEqualTo(ApplicationDraftException.Reason.MISSING_QUESTION_RESULT));}
    @Test void unknownCertificationIdFails(){assertUnknownPkbIds(List.of(81L),List.of(),List.of());}
    @Test void unknownEducationIdFails(){assertUnknownPkbIds(List.of(),List.of(82L),List.of());}
    @Test void unknownAwardIdFails(){assertUnknownPkbIds(List.of(),List.of(),List.of(83L));}
    @Test void repairThatStillExceedsLimitDoesNotRetry(){when(client.plan(any(),any(),anyList(),anyMap(),anyMap(),anyList(),anyList(),anyList(),anyList())).thenReturn(raw(draft("q",9L,List.of(),"123456")));when(client.repair(anyList(),anyList())).thenReturn(new RawApplicationDraftRepairResult(List.of(new RawQuestionRepair("q","12345"))));var q=service.draft(1L,request("q",3)).questions().getFirst();assertThat(q.draft()).isEqualTo("12345");assertThat(q.limitExceeded()).isTrue();verify(client,times(1)).repair(anyList(),anyList());}
    @Test void questionWithoutMaxLengthIsNeverRepairedOrExceeded(){when(client.plan(any(),any(),anyList(),anyMap(),anyMap(),anyList(),anyList(),anyList(),anyList())).thenReturn(raw(draft("q",9L,List.of(),"x".repeat(10_000))));var q=service.draft(1L,request("q",null)).questions().getFirst();assertThat(q.limitExceeded()).isFalse();assertThat(q.characterCount()).isEqualTo(10_000);verify(client,never()).repair(anyList(),anyList());}
    private ApplicationDraftRequest request(String id,Integer max){return new ApplicationDraftRequest(List.of(new QuestionRequest(id,"민감 문항 원문",max)));}
    private RawQuestionDraft draft(String id,Long primary,List<Long> supporting,String text){return new RawQuestionDraft(id,QuestionIntent.COLLABORATION,List.of(),primary,supporting,List.of(),List.of(),List.of(),"core",List.of("outline"),text,List.of(),false);}
    private RawQuestionDraft draftWithPkb(String id,List<Long> cert,List<Long> edu,List<Long> award){return new RawQuestionDraft(id,QuestionIntent.OTHER,List.of(),9L,List.of(),cert,edu,award,"core",List.of(),"draft",List.of(),false);}
    private void assertUnknownPkbIds(List<Long> cert,List<Long> edu,List<Long> award){when(client.plan(any(),any(),anyList(),anyMap(),anyMap(),anyList(),anyList(),anyList(),anyList())).thenReturn(raw(draftWithPkb("q",cert,edu,award)));assertThatThrownBy(()->service.draft(1L,request("q",null))).isInstanceOfSatisfying(ApplicationDraftException.class,e->assertThat(e.reason()).isEqualTo(ApplicationDraftException.Reason.UNKNOWN_CANDIDATE_ID));}
    private RawApplicationDraftResult raw(RawQuestionDraft... drafts){return new RawApplicationDraftResult(new RawOverallStrategy("position",List.of()),List.of(drafts));}
    private AgentAnalysisResponse strategy(){return new AgentAnalysisResponse(1L,"",List.of(),List.of(),"","",List.of(),List.of(),List.of(),List.of(),"agent only",List.of(),List.of(),List.of(),Instant.EPOCH);}
    private AgentAnalysisResponse strategyWithDifferentRecommendation(){var recommendation=new ExperienceRecommendation(77L,"AI/RAG 경험",1,.9,"AI relevance",List.of("RAG"),List.of());return new AgentAnalysisResponse(1L,"",List.of(),List.of(),"","",List.of(recommendation),List.of(),List.of(),List.of(),"agent only",List.of(),List.of(),List.of(),Instant.EPOCH);}
}
