package com.careerops.backend.agent.dto;

public enum AgentEvidenceSource {
    JOB_TITLE, JOB_CATEGORY, CAREER_LEVEL, EDUCATION_REQUIREMENT,
    EXPERIENCE_TAG, EXPERIENCE_TITLE, EXPERIENCE_SUMMARY, EXPERIENCE_DETAIL, EXPERIENCE_BULLET,
    CERTIFICATION_NAME, CERTIFICATION_DESCRIPTION,
    EDUCATION_MAJOR, EDUCATION_DESCRIPTION,
    AWARD_TITLE, AWARD_DESCRIPTION
}
