package com.careerops.backend.match.dto;

public enum EvidenceSource {
    JOB_TITLE, JOB_CATEGORY, CAREER_LEVEL, EDUCATION_REQUIREMENT,
    EXPERIENCE_TAG, EXPERIENCE_TITLE, EXPERIENCE_SUMMARY, EXPERIENCE_DETAIL,
    CERTIFICATION_NAME, CERTIFICATION_DESCRIPTION,
    EDUCATION_MAJOR, EDUCATION_DESCRIPTION,
    AWARD_TITLE, AWARD_DESCRIPTION
}
