import type { AgentEvidenceSourceType,ApplicationStatus,EvidenceSourceType,NotificationStatus,QuestionIntent } from "./types";
export const formatDate=(value:string|null,withTime=false)=>value?new Intl.DateTimeFormat("ko-KR",withTime?{dateStyle:"medium",timeStyle:"short"}:{dateStyle:"medium"}).format(new Date(value)):"—";
export const applicationLabel:Record<ApplicationStatus,string>={INTERESTED:"관심",PLANNED:"지원 예정",SUBMITTED:"지원 완료",OFFERED:"최종 합격",REJECTED:"불합격",WITHDRAWN:"지원 철회"};
export const notificationLabel:Record<NotificationStatus,string>={PENDING:"대기",SENDING:"처리 중",SENT:"완료",FAILED:"실패"};
export const stageTypeLabel={DOCUMENT:"서류",CODING_TEST:"코딩테스트",WRITTEN:"필기",INTERVIEW:"면접",FINAL:"최종",OTHER:"기타"} as const;
export const stageResultLabel={PENDING:"대기",PASSED:"합격",FAILED:"불합격",CANCELLED:"취소"} as const;
export const scoreLabel=(score:number)=>score.toFixed(2);
export const evidenceSourceLabel:Record<EvidenceSourceType,string>={JOB_TITLE:"공고 제목",JOB_CATEGORY:"직무 분류",CAREER_LEVEL:"경력 조건",EDUCATION_REQUIREMENT:"학력 조건",EXPERIENCE_TAG:"경험 태그",EXPERIENCE_TITLE:"경험 제목",EXPERIENCE_SUMMARY:"경험 요약",EXPERIENCE_DETAIL:"경험 상세",CERTIFICATION_NAME:"자격증명",CERTIFICATION_DESCRIPTION:"자격증 설명",EDUCATION_MAJOR:"전공",EDUCATION_DESCRIPTION:"학력 설명",AWARD_TITLE:"수상명",AWARD_DESCRIPTION:"수상 설명"};
export const agentEvidenceSourceLabel:Record<AgentEvidenceSourceType,string>={...evidenceSourceLabel,EXPERIENCE_BULLET:"경험 상세 기록"};
export const questionIntentLabel:Record<QuestionIntent,string>={SUPPORT_MOTIVATION:"지원 동기",JOB_COMPETENCY:"직무 역량",PROBLEM_SOLVING:"문제 해결",COLLABORATION:"협업",CONFLICT:"갈등 조정",GROWTH:"성장",VALUES:"가치관",AI_TECH:"AI·기술",OTHER:"기타"};
export const isClosingSoon=(date:string|null)=>{if(!date)return false;const today=new Date(Date.now());today.setHours(0,0,0,0);const target=new Date(`${date}T00:00:00`);const days=(target.getTime()-today.getTime())/86400000;return days>=0&&days<=7};
